// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	category "github.com/hanifbg/cud-category-product/service/category"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddCategory provides a mock function with given fields: _a0
func (_m *Service) AddCategory(_a0 category.CreateCategoryData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(category.CreateCategoryData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategory provides a mock function with given fields: id, name, isActive
func (_m *Service) UpdateCategory(id int, name string, isActive bool) error {
	ret := _m.Called(id, name, isActive)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, bool) error); ok {
		r0 = rf(id, name, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
