// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	checkout "github.com/hanifbg/cud-category-product/service/checkout"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateCheckout provides a mock function with given fields: _a0
func (_m *Repository) CreateCheckout(_a0 checkout.Checkout) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(checkout.Checkout) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
