// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	checkout "github.com/hanifbg/cud-category-product/service/checkout"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateCheckout provides a mock function with given fields: _a0, _a1
func (_m *Service) CreateCheckout(_a0 int, _a1 checkout.CreateCheckoutData) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, checkout.CreateCheckoutData) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
