// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	product "github.com/hanifbg/cud-category-product/service/product"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: _a0
func (_m *Service) AddProduct(_a0 product.CreateProductData) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(product.CreateProductData) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProduct provides a mock function with given fields: _a0, _a1
func (_m *Service) UpdateProduct(_a0 int, _a1 product.UpdateProduct) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, product.UpdateProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
